spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false    # Set to true only during development/debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

jwt:
  # Base64 encoded value of 'MySuperSecretKeyForJwtTokenThatShouldBeLongEnough12345'
  secret: TXlTdXBlclNlY3JldEtleUZvckp3dFRva2VuVGhhdFNob3VsZEJlTG9uZ0Vub3VnaDEyMzQ1
  expiration: 36000000  # 10 hours in milliseconds
